
## sources/references
## http://docs.travis-ci.com/user/getting-started/
## http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
## http://docs.travis-ci.com/user/build-configuration/#.travis.yml-file%3A-what-it-is-and-how-it-is-used
## Travis-CI social continuous intergration (T3CON12DE) https://www.youtube.com/watch?v=JicPX7K_dJs
## Testing Django with Travis CI https://www.youtube.com/watch?v=uFRJsbV8W_4#t=8m27s
## Testing .travis.yml files http://lint.travis-ci.org/

language: node_js
node_js:
 - "0.10"

install:
 #- npm install
 #- npm install gulp --global

script:
 #- gulp build

after_script:
 - openssl aes-256-cbc -K $encrypted_924df9a25462_key -iv $encrypted_924df9a25462_iv -in id_rsa.enc -out id_rsa -d
 - ls
 - chmod 600 id_rsa
 - ssh-add id_rsa
 - mkdir gh-pages
 - cd gh-pages
 - git init
 - git remote add origin http://github.com/$TRAVIS_REPO_SLUG.git
 - git checkout --orphan gh-pages
 - git pull origin gh-pages
 - echo "Hello World" > helloworld.txt
 #- mkdir $TRAVIS_BRANCH
 #- cd $TRAVIS_BRANCH
 #- rm -rf *
 #- cp ../../build/* .
 #- cd ..
 - git config --global user.name "Mocs Arcade"
 - git config --global user.email "mocsarcade@gmail.com"
 - git status
 - git add --all
 - git commit -m "Deployed $TRAVIS_BRANCH"
 - git push origin gh-pages
