language: node_js
node_js:
 - "0.10"

install:
 #- npm install
 #- npm install gulp --global

script:
 #- gulp build

after_script:
 - openssl aes-256-cbc -K $encrypted_924df9a25462_key -iv $encrypted_924df9a25462_iv -in deploy_key.enc -out deploy_key -d
 - cat deploy_key
 - chmod 600 deploy_key
 - eval `ssh-agent -s`
 - mv deploy_key id_rsa
 - ssh-add id_rsa
 - ssh -T git@github.com
 - mkdir gh-pages
 - cd gh-pages
 - git init
 - git remote add origin git@github.com/$TRAVIS_REPO_SLUG.git
 - git checkout --orphan gh-pages
 - git pull origin gh-pages
 - echo "Hello World" > helloworld.txt
 #- mkdir $TRAVIS_BRANCH
 #- cd $TRAVIS_BRANCH
 #- rm -rf *
 #- cp ../../build/* .
 #- cd ..
 - git config --global user.name "Mocs Arcade"
 - git config --global user.email "mocsarcade@gmail.com"
 - git status
 - git add --all
 - git commit -m "Deployed $TRAVIS_BRANCH"
 - git push origin gh-pages
